HunterPie/localization

localization/ja-jp.xml
Added missing strings and fixed syntax/spelling errors
=> Fix: ja-jp Loc for v2.5.0

localization/zh-cn.xml
=> Feat(localization): Missing monster names in zh-cn.xml

localization/zh-tw.xml
add
Monster Id 107 Risen Kushala Daora － 傀異克服鋼龍
Monster Id 109 Risen Teostra － 傀異克服炎王龍
Monster Id 113 Chaotic Gore Magala － 混沌黑蝕龍
translate
Arc Shot: Brace － 曲射:耐衝型
Arc Shot: Affinity － 曲射:會心型
The Frenzy (Buildup) － 狂龍症(感染)
=> zh-tw for v2.6.0

localization/es-mx.xml
Hi, while i was taking a look at the translations, i found some typos for the spanish language.
=> Fix: Typos in spanish

localization/ja-jp.xml
Additional Contributions by Geniti.jp#1766 and TYPE-XXX#9134
=> Feat: Updated ja-jp for MHR:S TU4, HunterPie v2.7.0

localization/en-us.xml, localization/ko-kr.xml
=> Fix: Separate Frostcraft name for MHW and MHR

localization/zh-cn.xml
Add missing zh-cn translation of monster parts based on en-us
=> Add missing zh-cn translation of monster parts based on en-us

localization/ja-jp.xml
added Risen Shagaru Magala, Amatsu, and Primordial Malzeno.
=> Added ver 15.00 and 16.00 new monster name for ja-jp

localization/zh-tw.xml
add 
Monster Id="110" String="傀異克服天迴龍"
Monster Id="112" String="原初爵銀龍"
Monster Id="115" String="嵐龍"
=> zh-tw for 2.9.0

localization/en-us.xml
Strings for https://github.com/HunterPie/HunterPie/pull/470
=> Feat(en-us): Added target mode strings

localization/ja-jp.xml
MHWilds monster names Japanese translation
=> feat(ja-jp):add MHWilds monster names

localization/zh-cn.xml
Sync the latest en-us.xml, add wilds palico song names, and update Simplified Chinese translations
=> feat(zh-cn): Sync the latest en-us.xml

localization/zh-tw.xml
Sync the latest en-us.xml.And corrected some translations.
=> feat(zh-tw): Sync the latest en-us.xml

localization/ja-jp.xml
=> feat(ja-jp) added mizutsune and variants for mhwilds

localization/zh-tw.xml
=> zh-tw added mizutsune for mhwilds

localization/zh-tw.xml
add monster parts and health toggle
=> feat(zh-tw): add monster parts and health toggle

localization/zh-tw.xml
=> feat(zh-tw): add moon phases

localization/ja-jp.xml
=> feat(ja-jp): add moon phases

localization/zh-tw.xml
add new specialized tools strings.
organize part of the format.
=> feat(zh-tw): add new specialized tools strings

localization/en-us.xml
=> feat(en-us): add omega

localization/ja-jp.xml
* Add Lagiacrus, Seregios and Omega
=> feat(ja-jp): Sync the latest en-us.xml

localization/en-us.xml
Kinda forgot Omega has a last name
=> Update monster name from 'Omega' to 'Omega Planetes'
